server:
  port: 80

token:
  access:
    expire_in_ms: 1800000
  refresh:
    expire_in_ms: 14400000

spring:
  application:
    name: user-management
#  security:
#    user:
#      name: admin
#      password: admin@123

  #Convert blank String to null
  jackson:
    deserialization:
      accept-empty-string-as-null-object: true

