apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  type: NodePort
  selector:
    app: user-management
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
